
# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

automation: !include automations.yaml
# automation ui: !include automations.yaml
# automation manual: !include_dir_merge_list automations/
script: !include scripts.yaml
scene: !include scenes.yaml
template: !include template.yaml
input_datetime: !include input_datetime.yaml
shell_command: !include shell_command.yaml

http:
  ip_ban_enabled: true
  login_attempts_threshold: 5
  use_x_forwarded_for: true
  trusted_proxies:
    - 192.168.1.3
    - 192.168.0.0/16
    - 172.30.33.0/24


